### ISSUE TITLE
InvalidArgumentException: No hint path defined for

### ISSUE THREAD

**Issue by northeaster** [askvortsov1/flarum-moderator-warnings#12]
The page failed when I created the warning. Error in log file:

```
[2020-11-10 18:36:35] flarum.ERROR: InvalidArgumentException: No hint path defined for [askvortsov-moderator-warnings]. in /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php:112
Stack trace:
#0 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments()
#1 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView()
#2 /var/www/html/flarum/vendor/illuminate/view/Factory.php(131): Illuminate\View\FileViewFinder->find()
#3 /var/www/html/flarum/vendor/illuminate/mail/Mailer.php(355): Illuminate\View\Factory->make()
#4 /var/www/html/flarum/vendor/illuminate/mail/Mailer.php(334): Illuminate\Mail\Mailer->renderView()
#5 /var/www/html/flarum/vendor/illuminate/mail/Mailer.php(246): Illuminate\Mail\Mailer->addContent()
#6 /var/www/html/flarum/vendor/flarum/core/src/Notification/NotificationMailer.php(51): Illuminate\Mail\Mailer->send()
#7 /var/www/html/flarum/vendor/flarum/core/src/Notification/Job/SendEmailNotificationJob.php(37): Flarum\Notification\NotificationMailer->send()
#8 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(36): Flarum\Notification\Job\SendEmailNotificationJob->handle()
#9 /var/www/html/flarum/vendor/illuminate/container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /var/www/html/flarum/vendor/illuminate/container/Container.php(590): Illuminate\Container\BoundMethod::call()
#13 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#14 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#15 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#17 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#18 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#19 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#21 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#22 /var/www/html/flarum/vendor/illuminate/queue/Jobs/Job.php(88): Illuminate\Queue\CallQueuedHandler->call()
#23 /var/www/html/flarum/vendor/illuminate/queue/SyncQueue.php(45): Illuminate\Queue\Jobs\Job->fire()
#24 /var/www/html/flarum/vendor/flarum/core/src/Notification/NotificationSyncer.php(163): Illuminate\Queue\SyncQueue->push()
#25 /var/www/html/flarum/vendor/flarum/core/src/Notification/NotificationSyncer.php(110): Flarum\Notification\NotificationSyncer->mailNotifications()
#26 /var/www/html/flarum/vendor/askvortsov/flarum-moderator-warnings/src/Api/Controller/CreateWarningController.php(89): Flarum\Notification\NotificationSyncer->sync()
#27 /var/www/html/flarum/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Askvortsov\FlarumWarnings\Api\Controller\CreateWarningController->data()
#28 /var/www/html/flarum/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\Api\Controller\AbstractSerializeController->handle()
#29 /var/www/html/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Api\Controller\AbstractCreateController->handle()
#30 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#31 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#32 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#33 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#34 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(45): Laminas\Stratigility\Next->handle()
#35 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#36 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\Stratigility\Next->handle()
#37 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#38 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#39 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#40 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#41 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#42 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#43 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#44 /var/www/html/flarum/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#45 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process()
#46 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#47 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#48 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#49 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#50 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#51 /var/www/html/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#52 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#53 /var/www/html/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#54 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#55 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#56 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#57 /var/www/html/flarum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#58 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#59 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#60 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#61 /var/www/html/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#62 /var/www/html/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#63 /var/www/html/flarum/index.php(26): Flarum\Http\Server->listen()
#64 {main}  
```

**Comment by askvortsov1** [comment]
That error happens when an extension booted prior to this one has the issue. Could you share `php flarum info`?

**Comment by northeaster** [comment]
I removed the extension. Should I install it again?

```
Flarum core 0.1.0-beta.14.1
PHP version: 7.4.12
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip
+---------------------------------+------------------+--------+
| Flarum Extensions               |                  |        |
+---------------------------------+------------------+--------+
| ID                              | Version          | Commit |
+---------------------------------+------------------+--------+
| flarum-approval                 | v0.1.0-beta.14   |        |
| flarum-bbcode                   | v0.1.0-beta.12   |        |
| flarum-emoji                    | v0.1.0-beta.14   |        |
| flarum-flags                    | v0.1.0-beta.14.1 |        |
| flarum-likes                    | v0.1.0-beta.14   |        |
| flarum-lock                     | v0.1.0-beta.14   |        |
| flarum-markdown                 | v0.1.0-beta.14   |        |
| flarum-mentions                 | v0.1.0-beta.14   |        |
| flarum-sticky                   | v0.1.0-beta.14   |        |
| flarum-subscriptions            | v0.1.0-beta.14   |        |
| flarum-suspend                  | v0.1.0-beta.14   |        |
| flarum-tags                     | v0.1.0-beta.14   |        |
| flarum-lang-english             | v0.1.0-beta.14.1 |        |
| flarum-statistics               | v0.1.0-beta.14   |        |
| fof-user-bio                    | 0.3.1            |        |
| tolgaaaltas-lang-turkish        | 0.14.1           |        |
| v17development-seo              | 1.4              |        |
| fof-follow-tags                 | 0.5.0            |        |
| fof-formatting                  | 0.2.0            |        |
| fof-split                       | 0.5.0            |        |
| tolgaaaltas-turkish             | 0.14.0           |        |
| nearata-signup-confirm-password | v2.1.0           |        |
| fof-forum-statistics-widget     | 0.3.0            |        |
| nearata-copy-code-to-clipboard  | v1.1.0           |        |
| fof-drafts                      | 0.2.0            |        |
| fof-best-answer                 | 0.2.0            |        |
| fof-links                       | 0.4.0            |        |
| fof-linguist                    | 0.4.4            |        |
| fof-terms                       | 0.5.0            |        |
| fof-merge-discussions           | 0.4.0            |        |
| fof-spamblock                   | 0.3.0            |        |
| fof-stopforumspam               | 0.3.1            |        |
| fof-geoip                       | 0.2.0            |        |
| fof-ban-ips                     | 0.3.0            |        |
| matteocontrini-imgur-upload     | v3.4.1           |        |
| fof-reactions                   | 0.4.2            |        |
| fof-profile-image-crop          | 0.2.0            |        |
| fof-pages                       | 0.5.0            |        |
| fof-nightmode                   | 0.6.0            |        |
| fof-github-autolink             | 0.1.4            |        |
| kyrne-shout                     | 0.2.4-beta.1     |        |
| clarkwinkelmann-author-change   | 0.2.1            |        |
| fof-filter                      | 0.1.0-beta.3     |        |
| fof-username-request            | 0.3.0            |        |
| nomiscz-auth-steam              | v0.2.0           |        |
| fof-oauth                       | 0.1.0            |        |
| michaelbelgium-discussion-views | v5.0.0           |        |
| michaelbelgium-profile-views    | v4.0.0           |        |
| fof-subscribed                  | 0.3.0            |        |
| fof-analytics                   | 0.10.0           |        |
+---------------------------------+------------------+--------+
Base URL: https://dursuncanpoyraz.com.tr/flarum
Installation path: /var/www/html/flarum
Debug mode: off
```

**Comment by askvortsov1** [comment]
One of these issues most likely has the improper view registration issue

**Comment by northeaster** [comment]
Other extensions do not log errors.

**Comment by askvortsov1** [comment]
This particular error happens as a result of previously booted extensions, not of the current one.

**Comment by northeaster** [comment]
If I share the php flarum info command information after installing the extension, can you find the problem?

**Comment by askvortsov1** [comment]
To find the error, you'll need to take a look at the extend.php files of all your extensions, and see if any are registering view namespaces via a closure instead of via the view extender.

**Comment by northeaster** [comment]
Can you write sample code?

**Comment by northeaster** [comment]
I found this command. I searched. This gave the results. These results have a continuation.

```
# grep -rnw /var/www/html/flarum/vendor -e 'namespaces'
/var/www/html/flarum/vendor/composer/ClassLoader.php:20: *     // register classes with namespaces
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:2817:     * Returns the SQL statement for retrieving the namespaces defined in the database.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:111:     * Returns a list of all namespaces in the current database.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:119:        $namespaces = $this->_conn->fetchAllAssociative($sql);
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:121:        return $this->getPortableNamespacesList($namespaces);
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:655:     * @param mixed[][] $namespaces The list of namespace names in the native DBMS data definition.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:659:    protected function getPortableNamespacesList(array $namespaces)
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:663:        foreach ($namespaces as $namespace) {
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1055:        $namespaces = [];
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1058:            $namespaces = $this->listNamespaceNames();
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1069:        return new Schema($tables, $sequences, $this->createSchemaConfig(), $namespaces);
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1102:     * The search path for namespaces in the currently connected database.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1105:     * further namespaces contain tables/sequences which can also be addressed
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1108:     * For databases that don't support subschema/namespaces this method
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:34: * databases being "misinterpreted" as namespaces. This is intentional, however
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:42:     * The namespaces in this schema.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:46:    private $namespaces = [];
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:60:     * @param string[]   $namespaces
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:66:        array $namespaces = []
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:75:        foreach ($namespaces as $namespace) {
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:148:     * Returns the namespaces of this schema.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:154:        return $this->namespaces;
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:227:        return isset($this->namespaces[$name]);
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:304:        if (isset($this->namespaces[$unquotedName])) {
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:308:        $this->namespaces[$unquotedName] = $name;
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:453:            foreach ($this->namespaces as $namespace) {
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php:18:     * All added namespaces.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php:25:     * All removed namespaces.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Visitor/NamespaceVisitor.php:6: * Visitor that can visit schema namespaces.
/var/www/html/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Visitor/RemoveNamespacedAssets.php:16: * non default namespaces.
/var/www/html/flarum/vendor/symfony/console/Application.php:552:     * Returns an array of all unique namespaces used by currently registered commands.
/var/www/html/flarum/vendor/symfony/console/Application.php:556:     * @return string[] An array of namespaces
/var/www/html/flarum/vendor/symfony/console/Application.php:560:        $namespaces = [];
/var/www/html/flarum/vendor/symfony/console/Application.php:566:            $namespaces = array_merge($namespaces, $this->extractAllNamespaces($command->getName()));
/var/www/html/flarum/vendor/symfony/console/Application.php:569:                $namespaces = array_merge($namespaces, $this->extractAllNamespaces($alias));
/var/www/html/flarum/vendor/symfony/console/Application.php:573:        return array_values(array_unique(array_filter($namespaces)));
/var/www/html/flarum/vendor/symfony/console/Application.php:589:        $namespaces = preg_grep('{^'.$expr.'}', $allNamespaces);
/var/www/html/flarum/vendor/symfony/console/Application.php:591:        if (empty($namespaces)) {
/var/www/html/flarum/vendor/symfony/console/Application.php:607:        $exact = \in_array($namespace, $namespaces, true);
/var/www/html/flarum/vendor/symfony/console/Application.php:608:        if (\count($namespaces) > 1 && !$exact) {
/var/www/html/flarum/vendor/symfony/console/Application.php:609:            throw new NamespaceNotFoundException(sprintf("The namespace \"%s\" is ambiguous.\nDid you mean one of these?\n%s.", $namespace, $this->getAbbreviationSuggestions(array_values($namespaces))), array_values($namespaces));
/var/www/html/flarum/vendor/symfony/console/Application.php:612:        return $exact ? $namespace : reset($namespaces);
/var/www/html/flarum/vendor/symfony/console/Application.php:653:        // if no commands matched or we just matched namespaces
/var/www/html/flarum/vendor/symfony/console/Application.php:1246:     * Returns all namespaces of the command name.
/var/www/html/flarum/vendor/symfony/console/Application.php:1248:     * @return string[] The namespaces of the command
/var/www/html/flarum/vendor/symfony/console/Application.php:1254:        $namespaces = [];
/var/www/html/flarum/vendor/symfony/console/Application.php:1257:            if (\count($namespaces)) {
/var/www/html/flarum/vendor/symfony/console/Application.php:1258:                $namespaces[] = end($namespaces).':'.$part;
/var/www/html/flarum/vendor/symfony/console/Application.php:1260:                $namespaces[] = $part;
/var/www/html/flarum/vendor/symfony/console/Application.php:1264:        return $namespaces;
/var/www/html/flarum/vendor/symfony/console/Descriptor/ApplicationDescription.php:34:    private $namespaces;
/var/www/html/flarum/vendor/symfony/console/Descriptor/ApplicationDescription.php:55:        if (null === $this->namespaces) {
/var/www/html/flarum/vendor/symfony/console/Descriptor/ApplicationDescription.php:59:        return $this->namespaces;
/var/www/html/flarum/vendor/symfony/console/Descriptor/ApplicationDescription.php:89:        $this->namespaces = [];
/var/www/html/flarum/vendor/symfony/console/Descriptor/ApplicationDescription.php:110:            $this->namespaces[$namespace] = ['id' => $namespace, 'commands' => $names];
/var/www/html/flarum/vendor/symfony/console/Descriptor/JsonDescriptor.php:87:            $data['namespaces'] = array_values($description->getNamespaces());
/var/www/html/flarum/vendor/symfony/console/Descriptor/TextDescriptor.php:203:            $namespaces = $description->getNamespaces();
/var/www/html/flarum/vendor/symfony/console/Descriptor/TextDescriptor.php:204:            if ($describedNamespace && $namespaces) {
/var/www/html/flarum/vendor/symfony/console/Descriptor/TextDescriptor.php:206:                $describedNamespaceInfo = reset($namespaces);
/var/www/html/flarum/vendor/symfony/console/Descriptor/TextDescriptor.php:215:            }, array_values($namespaces)))));
/var/www/html/flarum/vendor/symfony/console/Descriptor/TextDescriptor.php:223:            foreach ($namespaces as $namespace) {
/var/www/html/flarum/vendor/symfony/console/Descriptor/XmlDescriptor.php:102:            $rootXml->appendChild($namespacesXML = $dom->createElement('namespaces'));
/var/www/html/flarum/vendor/symfony/translation/Resources/schemas/xml.xsd:278:      if the XML Schema or XML namespaces change, the version of this
/var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/JavaScript/HintGenerator.php:199:               $this->hints['namespaces']            = 0;
/var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/JavaScript/HintGenerator.php:202:                       $this->hints['namespaces'] |= (strpos($tagName, ':') !== false);
/var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/RendererGenerators/XSLT.php:66:         // Declare all the namespaces in use at the top
/var/www/html/flarum/vendor/s9e/text-formatter/src/Configurator/RendererGenerators/XSLT.php:81:                 * @link http://lenzconsulting.com/namespaces-in-xslt/#exclude-result-prefixes
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.js:77:var namespaces;
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.js:240:       namespaces        = {};
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.js:370:       if (HINT.namespaces)
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.js:372:               for (var prefix in namespaces)
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.js:437:               if (HINT.namespaces)
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.js:442:                               namespaces[tagName.substr(0, colonPos)] = 0;
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.php:94:       protected $namespaces;
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.php:232:              $this->namespaces        = [];
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.php:431:              foreach (array_keys($this->namespaces) as $prefix)
/var/www/html/flarum/vendor/s9e/text-formatter/src/Parser.php:501:                              $this->namespaces[substr($tagName, 0, $colonPos)] = 0;
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/CHANGELOG.md:298:- [#32](https://github.com/laminas/laminas-zendframework-bridge/pull/32) changes all references to Apigility to instead reference Laminas API Tools. The vendor becomes laminas-api-tools, the URL becomes api-tools.getlaminas.org, packages and repos are prefixed with api-tools, and namespaces become `Laminas\ApiTools`.
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/CHANGELOG.md:468:- [#21](https://github.com/laminas/laminas-zendframework-bridge/pull/21) fixes how the recaptcha and twitter library package and namespaces are rewritten.
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/CHANGELOG.md:523:- [#12](https://github.com/laminas/laminas-zendframework-bridge/pull/12) adds functionality for ensuring we alias namespaces and classes that
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:87:    private static function createPrependAutoloader(array $namespaces, ClassLoader $classLoader, ArrayObject $loaded)
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:93:        return static function ($class) use ($namespaces, $classLoader, $loaded) {
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:103:            while (isset($segments[$i + 1], $namespaces[$check . $segments[$i] . '\\'])) {/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:113:                $legacy = $namespaces[$check]
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:127:    private static function createAppendAutoloader(array $namespaces, ArrayObject $loaded)/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:133:        return static function ($class) use ($namespaces, $loaded) {
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:146:            while (isset($segments[$i + 1], $namespaces[$check . $segments[$i] . '\\'])) {/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:155:            $alias = $namespaces[$check]
/var/www/html/flarum/vendor/laminas/laminas-zendframework-bridge/src/Module.php:35:     * Rewrites keys and values matching known ZF classes, namespaces, and
/var/www/html/flarum/vendor/guzzlehttp/guzzle/CHANGELOG.md:1078:* Broke the project into smaller top-level namespaces to be more component friendly
/var/www/html/flarum/vendor/guzzlehttp/guzzle/CHANGELOG.md:1255:* Allowing the use of dot notation for class namespaces when using instance_of constraint
/var/www/html/flarum/vendor/guzzlehttp/guzzle/UPGRADING.md:229:- Various namespaces have been removed or renamed.
/var/www/html/flarum/vendor/illuminate/contracts/Translation/Loader.php:35:     * Get an array of all the registered namespaces.
/var/www/html/flarum/vendor/illuminate/contracts/Translation/Loader.php:39:    public function namespaces();
/var/www/html/flarum/vendor/illuminate/translation/ArrayLoader.php:73:     * Get an array of all the registered namespaces.
/var/www/html/flarum/vendor/illuminate/translation/ArrayLoader.php:77:    public function namespaces()
/var/www/html/flarum/vendor/illuminate/translation/FileLoader.php:179:     * Get an array of all the registered namespaces.
/var/www/html/flarum/vendor/illuminate/translation/FileLoader.php:183:    public function namespaces()
```

**Comment by northeaster** [comment]
```
]# grep -rnw /var/www/html/flarum/vendor -e '->namespace'
/var/www/html/flarum/vendor/flarum/mentions/extend.php:45:        ->namespace('flarum-mentions', __DIR__.'/views'),
/var/www/html/flarum/vendor/flarum/subscriptions/extend.php:36:        ->namespace('flarum-subscriptions', __DIR__.'/views'),
/var/www/html/flarum/vendor/flarum/tags/extend.php:45:        ->namespace('tags', __DIR__.'/views'),
/var/www/html/flarum/vendor/fof/best-answer/extend.php:51:        ->namespace('fof-best-answer', __DIR__.'/resources/views'),
/var/www/html/flarum/vendor/fof/pages/extend.php:43:        ->namespace('fof-pages', __DIR__.'/resources/views'),
/var/www/html/flarum/vendor/fof/filter/extend.php:24:        ->namespace('fof-filter', __DIR__.'/views'),
/var/www/html/flarum/vendor/fof/subscribed/extend.php:28:        ->namespace('fof-subscribed', __DIR__.'/resources/views'),
/var/www/html/flarum/vendor/fof/follow-tags/extend.php:46:        ->namespace('fof-follow-tags', __DIR__.'/resources/views'),
```

**Comment by clarkwinkelmann** [comment]
I think looking for `->namespace` will only find usage of the new correct extender.

You could look for `->addNamespace` to find usage of the improper code.

**Comment by northeaster** [comment]
@clarkwinkelmann I disabled the fof/filter extension. `php flarum fof:sitemap:cache --write-xml-file` command worked without error.

```
# php flarum fof:sitemap:cache --write-xml-file

In FileViewFinder.php line 112:
                                           
  No hint path defined for [fof-sitemap].  
                                           

fof:sitemap:cache [--write-xml-file] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command>

[root@www flarum]# cd ./storage/logs
[root@www logs]# ls
flarum-2020-11-15.log
[root@www logs]# cat flarum-2020-11-15.log 
[2020-11-15 18:42:04] flarum.ERROR: InvalidArgumentException: No hint path defined for [fof-sitemap]. in /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php:112
Stack trace:
#0 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments()
#1 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView()
#2 /var/www/html/flarum/vendor/illuminate/view/Factory.php(131): Illuminate\View\FileViewFinder->find()
#3 /var/www/html/flarum/vendor/fof/sitemap/src/Commands/CacheSitemapCommand.php(35): Illuminate\View\Factory->make()
#4 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(36): FoF\Sitemap\Commands\CacheSitemapCommand->handle()
#5 /var/www/html/flarum/vendor/illuminate/container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#7 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#8 /var/www/html/flarum/vendor/illuminate/container/Container.php(590): Illuminate\Container\BoundMethod::call()
#9 /var/www/html/flarum/vendor/illuminate/console/Command.php(134): Illuminate\Container\Container->call()
#10 /var/www/html/flarum/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#11 /var/www/html/flarum/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#12 /var/www/html/flarum/vendor/symfony/console/Application.php(1027): Illuminate\Console\Command->run()
#13 /var/www/html/flarum/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/html/flarum/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#15 /var/www/html/flarum/vendor/flarum/core/src/Console/Server.php(42): Symfony\Component\Console\Application->run()
#16 /var/www/html/flarum/flarum(24): Flarum\Console\Server->listen()
#17 {main}  
[root@www logs]# rm flarum-2020-11-15.log 
rm: remove regular file 'flarum-2020-11-15.log'? y
[root@www logs]# cd ../..
[root@www flarum]# php flarum fof:sitemap:cache --write-xml-file
[root@www flarum]# grep -rnw /var/www/html/flarum/vendor -e '->addNamespace'
```

**Comment by northeaster** [comment]
The error seems to be fixed. Do you declare to the fof/filter extension? caused the same error on multiple extensions.

**Comment by askvortsov1** [comment]
@northeaster what happens when you run `grep -rnw /var/www/html/flarum/vendor -e '->addNamespace`

**Comment by northeaster** [comment]
When I typed the command it couldn't find anything.

**Comment by askvortsov1** [comment]
Did you run it before or after removing fof filter?

**Comment by northeaster** [comment]
with fof filter extension disabled
